### ISSUE TITLE
Setuptools Entry Point Target Incorrect

### ISSUE THREAD

**Issue by mobiusklein** [draperjames/unfinnigan#1]
The entry point registered in `setup.py` points to a module, not a function:

https://github.com/draperjames/unfinnigan/blob/master/setup.py#L66
`'unfinnigan=unfinnigan:unfinnigan'`

```
Traceback (most recent call last):
  File "c:\users\user\miniconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\user\miniconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\User\Miniconda2\Scripts\unfinnigan.exe\__main__.py", line 9, in <module>
TypeError: 'module' object is not callable
```
I think it should be `unfinnigan=unfinnigan.unfinnigan:main`.

As an aside, what is the scope of this project? To get a full raw file parser that doesn't depend on Thermo's MSFileReader/RawFileReader, or just to be able to read specific pieces of metadata?

**Comment by draperjames** [comment]
@mobiusklein I think you're correct I'll change that try push it up to pip when I have some free time. As far as the scope of the project that is a little bit complicated I just repacked @selkovjr 's [unfinnigan](https://github.com/selkovjr/unfinnigan) and uploaded it to pip. I took the liberty of doing that because it appeared that the project had gone dormant and I wanted to try to breath some life back into it but time got away from me. I just noticed there is very nice documentation on the [OG wiki branch](https://github.com/selkovjr/unfinnigan/tree/wiki). Short answer long I believe that this project has the potential to be a raw file parser that doesn't rely on Thermo's MSFileReader/RawFileReader, but I have had limited success getting it to work with the raw files that come off the QE+. Thank you for interest and the suggestion if you would like to discuss this further please email me at james.draper[at]protonmail.com.

Best regards,
-JAD
